// Auto-generated by generatedTypes. Do not edit manually.

export type Users = {
  id: string;
  displayName: string;
  firstName: string;
  lastName: string;
  email: string;
  createdAt: firebase.firestore.Timestamp;
};

