// Auto-generated by generatedTypes. Do not edit manually.

export type Users = {
  id: string;
  firstName: string;
  lastName: string;
  username: string;
  email: string;
  createdAt: timestamp;
};
