name: PR - Build and Test

# Trigger the workflow on push or pull request to the main branch
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: yarn

      - name: Setup Expo
        working-directory: ./FlockRN
        run: |
          yarn install
          yarn global add expo-cli

      - name: Run tests
        working-directory: ./FlockRN
        run: |
          yarn test

      - name: Lint code
        working-directory: ./FlockRN
        run: |
          yarn lint

      # Build Android APK
      - name: Build Android APK
        working-directory: ./FlockRN
        run: |
          expo build:android --no-publish --non-interactive

      # Build iOS IPA (Note: Requires macOS runner)
      - name: Build iOS IPA
        working-directory: ./FlockRN
        run: |
          expo build:ios --no-publish --non-interactive
