name: Build Project

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Expo
        working-directory: ./FlockRN # Set working directory for this step
        run: |
          yarn install
          yarn global add expo-cli

      # Build Android APK
      - name: Build Android APK
        working-directory: ./FlockRN # Set working directory for this step
        run: |
          expo build:android --no-wait  # Modify this for your specific build command

      # Build iOS IPA (Note: Requires macOS runner)
      - name: Build iOS IPA
        working-directory: ./FlockRN # Set working directory for this step
        run: |
          expo build:ios --no-wait  # Modify this for your specific build command

      # Add additional steps to verify the build (e.g., run tests, linting, etc.)
      - name: Run tests
        working-directory: ./FlockRN # Set working directory for this step
        run: |
          yarn test  # Or run your test commands if applicable

      - name: Lint code
        working-directory: ./FlockRN # Set working directory for this step
        run: |
          yarn lint  # Or run linting commands if applicable
